### ISSUE TITLE
Can't build in Windows

### ISSUE THREAD

**Issue by ghishadow** [nheuillet/lapce-go#2]
Getting this error when trying to build on Windows

![image](https://user-images.githubusercontent.com/9583775/176738818-d2c880a4-a3b5-4683-9d29-cab7aca5a1d2.png)

**Comment by ghishadow** [comment]
ok `cargo wasi build` worked

**Comment by nheuillet** [comment]
I should probably start rolling release builds soon either way, it would help newcomers
